import Head from 'next/head';

const HeadMeta = () => {
  return (
    <Head>
      <title>Johnny</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default HeadMeta;
